### ISSUE TITLE
Please release a new version :)

### ISSUE THREAD

**Issue by tomas-zijdemans** [kotest/kotest-extensions-wiremock#43]
This PR: https://github.com/kotest/kotest-extensions-wiremock/pull/41 will upgrade wiremock to 3.6.0 (from 3.3.1 i believe). 

In version 3.5 of wiremock there was an important bugfix that is effecting a lot of users, including us: https://github.com/wiremock/wiremock/pull/2629

**Comment by Kantis** [comment]
Should be done now. Let me know if you have any issues with it

**Comment by tomas-zijdemans** [comment]
That's awesome. Thank you!
